### ISSUE TITLE
Create function to save data collected from the API

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#11]
The API call function returns a dataframe which is not persistent. The data needs to be stored in a format that will be accessible later. 

Suggestions:
- initially look at [feather ](https://arrow.apache.org/docs/python/feather.html?msclkid=579b7350b66f11ecb7aa8599f8c3708d) because it's fast and lightweight. In which case you will need [pd.to_feather()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_feather.html?highlight=feather#pandas.DataFrame.to_feather) and [pd.read_feather()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_feather.html?highlight=feather)
- For longer term storage, look at [postgresql](https://www.postgresql.org/) which is well supported in Python

**Comment by chloemurrell** [comment]
Additional Requirements
- The data storage needs to be cumulative and not overwrite old data. 
- Data needs to be stored based on location or have a location column eg. London and Grimsby separately.

**Comment by jwestw** [comment]
We have discovered that feather is a columnar-oriented file format so we cannot "append". We think therefore that hdf5 might be better for iteratively writing out. 

Pandas has a function for this [pandas.HDFStore.append()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.HDFStore.append.html)

**Comment by chloemurrell** [comment]
Also add additional column for arrival time period (eg. weekday morning)

**Comment by chloemurrell** [comment]
Complete this ticket as the API results are saved to a h5 file which can be exported to excel. Additional columns (arrival time period and location) will be added in along with the config as this will be easiest.
