### ISSUE TITLE
Create a geospatial function to convert coordinates

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#40]
There are different coordinate reference systems (CRS) and we sometimes need to translate from one system to another. All our data needs to be in one CRS. Since the API uses latitude and longitude, whatever that system is, we should use it.

When we get data in Northings and Eastings we will need to translate that over to Lat and Long.

I suggest using Geopandas ([to_crs method](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_crs.html)), but what's underlying that is [Pyproj](https://pyproj4.github.io/pyproj/stable/index.html), so if you wanted you could use Pyproj directly. To change the crs you'd need to use a [transformer](https://pyproj4.github.io/pyproj/stable/api/transformer.html). There is a method detailed on [this Stackexhange ](https://gis.stackexchange.com/questions/78838/converting-projected-coordinates-to-lat-lon-using-python)post. 

**Requirements**:
- Have parameters `crs_from` and a `crs_to` which will indicate the coordinate that are being translated to and from
- Be able to at least translate from Northing/Easting to Lat/Long and back again
- Take a pandas dataframe or a geopandas geodataframe as input data
- Return the same datatype as the input
- Create a docstring
- Test that your function works

Helpful code may be found in my [other project here](https://github.com/ONSdigital/SDG_11.2.1/blob/6780109ff96df45c2c5d99c05baa725c4f5f54ef/data_ingest.py#L268).

Note there are many [Spatial reference codes at spatialreference.org](https://spatialreference.org/ref/?page=2).

**Comment by chloemurrell** [comment]
This ticket has been completed - see function convert_coordinates.
