### ISSUE TITLE
Create a config file and config parser for the script

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#42]
Use either TOML or yaml to create config file that can take parameters into the script, making it easier for the user to choose how the script is run. 

Parameters to abstract into the config file:
- path to the points of interest file
- city name
- travel time
- arrival time period (e.g. week day morning --- giving the user the options commented out)
- location to write out to (data folder, path)
- option to write out to Excel
- option to overwrite the Excel file

Your config file might look like this:
```yaml
write_to_excel = true
overwrite_excel = false
```

```python
# some code to read in the yaml or toml

if overwrite_excel:
    if write_to_excel:
       pd.to_excel()
else:
    if os.is_file(file_path):
         pd.to_excel()
```

**Comment by chloemurrell** [comment]
Additional Requirements: 
Add "Location" column and "Arrival Time Period" column. 
https://github.com/jwestw/Public_Transport_Efficiency/issues/11#issuecomment-1175161557
