### ISSUE TITLE
Divide the get_results_from_api  function

### ISSUE THREAD

**Issue by chloemurrell** [jwestw/Public_Transport_Efficiency#53]
This function is very long and completes multiple tasks. 

To make it easier to use and develop it would be best to split this function into two. One which calls the api and one which processes the results. The two new functions will need updated Doc Strings. 

It may also be useful to have the private and public parameter dictionaries within the config.

**Comment by james-westwood** [comment]
## Steps for the developer

- make a branch 
- Look at the `get_results_from_api` function
- Plan your code
  - Split it up into separate functions that "do one thing" (see more details below). There are various ways to split this up.
  - Open a discussion (in the comments here) if you want ideas
  - Consider drawing a diagram for how this will work - use Gliphy on confluence
- Lay down some code
- Add/commit/push
- Create a PR and request a review 

### Link to the code

-  https://github.com/jwestw/Public_Transport_Efficiency/blob/3b3d207c40bb9b4fef80419fc645c10b94a697b0/Call_API_code.py#L121

### Notes on good practice when creating functions

You want each function to:
- be small
- do one thing
- contain code with the same level of abstraction
- have fewer than 4 arguments
- have no duplication
- use descriptive names
