### ISSUE TITLE
Get environment set up 

### ISSUE THREAD

**Issue by penbet** [jwestw/Public_Transport_Efficiency#60]
- Get environment successfully set up on my desktop.
- Reslve problem surrounding setting up yaml
- Update Read.me according to any problems found

**Comment by penbet** [comment]
Perhaps solved environment issue with following code - conda env update --file environment.yml --name transp_eff_310 @chloemurrell @james-westwood 

Ran script but ended after a whle with error Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement traveltimepy==0.2 (from versions: none)
ERROR: No matching distribution found for traveltimepy==0.2

failed

CondaEnvException: Pip failed

**Comment by james-westwood** [comment]
>Perhaps solved environment issue with following code - conda env update --file environment.yml --name transp_eff_310 @chloemurrell @james-westwood

Perfect!

>Ran script but ended after a whle with error Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement traveltimepy==0.2 (from versions: none)
ERROR: No matching distribution found for traveltimepy==0.2

>failed

>CondaEnvException: Pip failed

Less good. But I think you can solve this with `pip install git+https://github.com/traveltime-dev/traveltime-python-sdk`
@chloe-murrell would you agree? 

@penbet If this is the solution, please add that as an extra step in the readme.

**Comment by penbet** [comment]
yes above code worked, and think everything else has gone smoothly too. I'll take some time out next week to update the read.me (and double ceck I have everything working properly), and perhaps leave some other suggestions from going through it.
