### ISSUE TITLE
Set up pre-commits

### ISSUE THREAD

**Issue by jwestw** [jwestw/Public_Transport_Efficiency#9]
Pre-commits  are a really useful tool for us to keep our code clean and standardised. They therefore should be a developer requirement on this project. 

- [x] Make a branch well named branch
- [x] Keep notes for a simple/brief write up 
- [x] Go to [pre-commits.com install instructions ](https://pre-commit.com/#installation) and follow the instructions for your OS
- [x] [Install flake8](https://flake8.pycqa.org/en/latest/#installation) (inside your activated virtual environment)
- [x] Configure flake8 (see below)
- [x] Create a `.pre-commit-config.yaml` following the instructions
- [x] Update the README how you did that and how other developers can do the same
- [x] Add the README,  commit changed file
    - This only needs to be really brief and should mainly be linking to the pre-commit official documentation  
- [x] Add  the `.pre-commit-config.yaml`,  commit changed files
- [x] Make a PR into `develop`

### Hooks which I think are very useful or essential:
- trailing-whitespace
- detect-private-key
- end-of-file-fixer
- flake8 (not auto-correcting, but just advising where the problems are)

### Configuring flake8

For flake8 to work you need to [configure it](https://flake8.pycqa.org/en/latest/user/configuration.html). I am not sure if you need to install it (I think not because the pre-commits script runs it from the `repo` URL).

I appreciate this ticket might be a bit tricky so if you get stuck with any part, please get in contact.

**Comment by jwestw** [comment]
These are the error codes which might be useful for configuring flake8:

- [PEP8 error codes](http://pep8.readthedocs.io/en/latest/intro.html#error-codes).
- [PyFlakes error codes](https://flake8.pycqa.org/en/latest/user/error-codes.html).
- [PEP8 Naming error codes](https://github.com/PyCQA/pep8-naming#error-codes).

**Comment by chloemurrell** [comment]
This issue is completed.
